#IN THIS WE WILL SEE DEMONSTRATION OF filter(), map(),reduce()

#filter(func,seq)-returns the sequence
#ques- create list divisible by 2 and 4 between 2-22

#without using filter
div_2_4=[]             #created empty list
for x in range(2,22):  #checking the condition
    if(x%2==0 or x%4==0):
        div_2_4.append(x) #if found appending the value in empty list
print(div_2_4)

#using filter
def check(x):
    if(x%2==0 or x%4==0):
        return 1
y=list(filter(check,range(2,44))) # firstly makes empty list then filter it acc to if loop then checks the given range
print(y)



#map() func - call function(item) for each item in the sequnce and returns the list
def add_2(x):
    x+=2
    return x
num = [3,4,5,6]
n_list = list(map(add_2,num))
print(n_list)



#reduce() - returns single value generated by the cslling of the func on the first two items , then on the result and the next item
#eg - [2,3,4,5] = 2+3=5 -> 5+4 =9 -> 9+5 =14
import functools
def add(x,y):
    return x+y
n =[2,3,4,5]
print("sum ", functools.reduce(add,n))


